### ISSUE TITLE
traceback when using library

### ISSUE THREAD

**Issue by kdschlosser** [pikhovkin/simple-websocket-server#1]
I am getting this traceback using your sample code running on python 3.5 Windows 7 X64 SP1

```python
Traceback (most recent call last):
  File "C:\Stackless35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Stackless35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Stackless35\lib\site-packages\simple_websocket_server\__init__.py", line 658, in serve_forever
    self.handle_request()
  File "C:\Stackless35\lib\site-packages\simple_websocket_server\__init__.py", line 598, in handle_request
    r_list, w_list, x_list = select(self.listeners, writers, self.listeners, self.selectInterval)
ValueError: file descriptor cannot be a negative integer (-1)
```

this traceback occurs right away.

**Comment by pikhovkin** [comment]
https://github.com/dpallot/simple-websocket-server/issues/91
